
PUT {{host}}/api/flashcards/{{flashcard_id_to_test}}
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
    "question": "updating this to verify something??",
    "answer": "Very much so! This is updated :D"
}