
POST {{host}}/api/flashcards/{{flashcard_id_to_test}}/review-schedule
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "newLastReviewed": "2025-05-11T00:00:00",
  "newNextReview": "2025-05-19T09:00:40.7171524"
}